service: boa-graphql # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

# you can define service wide environment variables here
#  environment:
#    variable1: value1

package:
  exclude:
    - node_modules/**/*
  include:
    src/lambda.ts

functions:
  hello:
    handler: src/lambda.handler
    events:
      - http:
          path: graphql
          method: post

plugins:
  - serverless-plugin-typescript
  - serverless-offline
