service: boa-graphql # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-2
  stage: ${opt:stage, 'dev'}

custom: ${file(conf.${self:provider.stage}.yml)}

package:
  exclude:
    - "**/*.js.map"
  include:
    - src/lambda.js
    - ormconfig.js

functions:
  hello:
    handler: src/lambda.handler
    events:
      - http:
          path: graphql
          method: post
    vpc:
      securityGroupIds:
        - sg-0291bd8d1e232f49f
      subnetIds:
        - subnet-0b97ee17592881f18
        - subnet-0fc7236de087f7873
    environment:
      TYPEORM_HOST: ${self:custom.TYPEORM_HOST}
      TYPEORM_USERNAME: ${self:custom.TYPEORM_USERNAME}
      TYPEORM_PASSWORD: ${self:custom.TYPEORM_PASSWORD}
      TYPEORM_DATABASE: ${self:custom.TYPEORM_DATABASE}
      BASE_DIR: ${self:custom.BASE_DIR}
      STAGE: ${self:provider.stage}

plugins:
  - serverless-plugin-typescript
  - serverless-offline
