service: boa-graphql # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-2
  stage: ${opt:stage, 'dev'}
  environment:
    TYPEORM_HOST: ${self:custom.TYPEORM_HOST}
    TYPEORM_USERNAME: ${self:custom.TYPEORM_USERNAME}
    TYPEORM_PASSWORD: ${self:custom.TYPEORM_PASSWORD}
    TYPEORM_DATABASE: ${self:custom.TYPEORM_DATABASE}

custom: ${file(conf.${self:provider.stage}.yml)}

package:
  exclude:
    - src/**

functions:
  graphql:
    handler: src/lambda/graphql.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
          authorizer: jwtAuth
    vpc:
      securityGroupIds: ${self:custom.SECURITY_GROUPS}
      subnetIds: ${self:custom.SUBNETS}
    environment:
      BASE_DIR: ${self:custom.BASE_DIR}
      STAGE: ${self:provider.stage}
    package:
      include:
        - src/lambda/graphql.js
        - ormconfig.js

  postConfirm:
    handler: src/lambda/postConfirm.handler
    vpc:
      securityGroupIds: ${self:custom.SECURITY_GROUPS}
      subnetIds: ${self:custom.SUBNETS}
    package:
      include:
        - src/lambda/postConfirm.js

  jwtAuth:
    handler: src/lambda/jwtAuth.handler
    vpc:
      securityGroupIds: ${self:custom.SECURITY_GROUPS}
      subnetIds: ${self:custom.SUBNETS}
    package:
      include:
        - src/lambda/jwtAuth.js
    
plugins:
  - serverless-plugin-typescript
  - serverless-offline
