service: boa-graphql # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-2
  stage: ${opt:stage, 'dev'}
  environment:
    TYPEORM_HOST: ${self:custom.TYPEORM_HOST}
    TYPEORM_USERNAME: ${self:custom.TYPEORM_USERNAME}
    TYPEORM_PASSWORD: ${self:custom.TYPEORM_PASSWORD}
    TYPEORM_DATABASE: ${self:custom.TYPEORM_DATABASE}

custom: ${file(conf.${self:provider.stage}.yml)}

package:
  include:
    - src/lambda/jwtAuth.js
    - src/lambda/graphql.js
    - src/lambda/postConfirm.js
    - ormconfig.js
  exclude:
    - "**/*.js.map"

functions:
  graphql:
    handler: src/lambda/graphql.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
    vpc:
      securityGroupIds: ${self:custom.SECURITY_GROUPS}
      subnetIds: ${self:custom.SUBNETS}
    environment:
      BASE_DIR: ${self:custom.BASE_DIR}
      STAGE: ${self:provider.stage}

  postConfirm:
    handler: src/lambda/postConfirm.handler
    vpc:
      securityGroupIds: ${self:custom.SECURITY_GROUPS}
      subnetIds: ${self:custom.SUBNETS}

  preToken:
    handler: src/lambda/preToken.handler
    vpc:
      securityGroupIds: ${self:custom.SECURITY_GROUPS}
      subnetIds: ${self:custom.SUBNETS}

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId: 
          Ref: 'ApiGatewayRestApi'

plugins:
  - serverless-plugin-typescript
  - serverless-offline
