version: 2
jobs:
  install:
    docker:
      - image: circleci/node:11.6.0
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
  deploy:
    docker:
      - image: circleci/node:11.6.0
    steps:
      - checkout
      - deploy:
          name: serverless-deploy
          command: npm run deploy
workflows:
  version: 2
  deploy:
    jobs:
      - install
      - deploy:
          requires:
            - install
          filters:
            branches:
              only: master
