version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:11.6.0
    steps:
      - checkout
      - run:
          name: npm-install
          command: npm install
      - deploy:
          name: serverless-deploy
          command: npm deploy
